apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloworld-python-route
  namespace: kustomize-test
spec:
  host: helloworld-python.local
  to: 
    kind: Service
    name: helloworld-python
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect